#!/usr/bin/env sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        # No homebrew? Weird
        echo "Installing homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    # Homebrew is installed, do the thing
fi

